spring:
  application:
    name: playing-together
  datasource:
    url: jdbc:h2:~/database/h2db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  ai:
    openai:
      api-key: ${SPRING_AI_OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o
          response-format: json_object
          temperature: 0.0
    retry:
      max-attempts: 2

server:
  error:
    include-message: always
    include-binding-errors: always
