name: Deploy to AWS beanstalk

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml

      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: playing-together-jar
          path: target/playing-together-0.0.1-SNAPSHOT.jar

  deploy:
    needs: build
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download JAR
        uses: actions/download-artifact@v2
        with:
          name: playing-together-jar

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTION_ROLE }}

      - name: Upload jar to s3
        run: aws s3 cp ./playing-together-0.0.1-SNAPSHOT.jar ${{ vars.AWS_S3_PATH }}
